### ISSUE TITLE
X11 dependency

### ISSUE THREAD

**Issue by FabriceSalvaire** [conda-forge/ngspice-feedstock#1]
Is is possible to split the package so as to have X11 ngspice in another one ???

**Comment by stuarteberg** [comment]
Yes, I think this is possible. I don’t have time to do it today, unfortunately.

**Comment by stuarteberg** [comment]
The `ngspice` executable depends on X11, but `libngspice` does not.  I will need to change the recipe so that it produces two different packages.  I know this is possible to do from a single recipe, but I haven't done it before.
