### ISSUE TITLE
Add configure setup in README

### ISSUE THREAD

**Issue by FabriceSalvaire** [conda-forge/ngspice-feedstock#2]
I checked the compilation setup is ok, it would be useful to add the configure setup in the readme, just because it is important for serious projects.

**Comment by stuarteberg** [comment]
Ah yes.  I hope this package can be useful for any `ngspice` user (not just PySpice users).  But I noticed your advice in the [PySpice docs][1] regarding the best configuration to use, so I just copied that.

[1]: https://pyspice.fabrice-salvaire.fr/installation.html#ngspice-compilation

And with #4, it is now documented in the feedstock readme.
