### ISSUE TITLE
Possible issue on Centos 6 & 7

### ISSUE THREAD

**Issue by FabriceSalvaire** [conda-forge/ngspice-feedstock#3]
I got a compilation error on Centos 6 & 7 for v32 when I rebuilded the RPM packages of my copr repository https://copr.fedorainfracloud.org/coprs/fabricesalvaire/ngspice/

**Comment by stuarteberg** [comment]
Sorry, I don't understand how this relates to the conda-forge build of PySpice.  Am I missing something?

**Comment by stuarteberg** [comment]
Thanks for the warning.  I've created a PR #5 to test v32.  I will check on its build result later.

**Comment by stuarteberg** [comment]
Looks like that PR passes, so I merged it.  So conda-forge now contains ngspice 32 (for mac and linux).
