### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/ngspice-feedstock#6]
Would be great to have windows support.  [This comment explains][1] how to get started.  There is a chance that @endolith is going to work on this, so it might be worth pinging him before starting an independent effort.

[1]: https://github.com/FabriceSalvaire/PySpice/issues/188#issuecomment-624673661

**Comment by endolith** [comment]
There is a _chance_, yes.... but anyone else is free to beat me to it.

**Comment by stuarteberg** [comment]
I added Windows support to the recipe, but it requires more testing by someone with a Windows machine.  I'm also in the process of [adding Windows support to the PySpice recipe][1], which will automatically test `ngspice.dll`, at least.

[1]: https://github.com/conda-forge/pyspice-feedstock/pull/5

(That PR isn't passing yet because the `ngspice` packages haven't yet propagated through Anaconda's CDN.  I'll re-run the CI checks tomorrow.)

**Comment by stuarteberg** [comment]
Well, the PySpice recipe now passes on Windows, which I'll take as good-enough confirmation that the ngspice Windows recipe is built properly.  Closing now.  If someone discovers a problem, we can reopen this.

BTW, Unlike our Mac/Linux build, our Windows build isn't compiled with X11 support.  In theory, I think it could be added because conda-forge's [`x11 recipe`](https://github.com/conda-forge/xorg-libx11-feedstock/blob/master/recipe/meta.yaml) apparently supports Windows.  But I don't even own a Windows machine, so I'm not in a good position to fiddle around with that.

**Comment by stuarteberg** [comment]
Shout-out to @seanyen for contributing the `winflexbison` recipe to conda-forge.  Thanks!  I couldn't have added Windows support to this package without it.
